################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../LIB/Lib_canard_func/src/uavcan.CoarseOrientation.c \
../LIB/Lib_canard_func/src/uavcan.Timestamp.c \
../LIB/Lib_canard_func/src/uavcan.equipment.actuator.ArrayCommand.c \
../LIB/Lib_canard_func/src/uavcan.equipment.actuator.Command.c \
../LIB/Lib_canard_func/src/uavcan.equipment.actuator.Status.c \
../LIB/Lib_canard_func/src/uavcan.equipment.ahrs.MagneticFieldStrength.c \
../LIB/Lib_canard_func/src/uavcan.equipment.ahrs.MagneticFieldStrength2.c \
../LIB/Lib_canard_func/src/uavcan.equipment.ahrs.RawIMU.c \
../LIB/Lib_canard_func/src/uavcan.equipment.ahrs.Solution.c \
../LIB/Lib_canard_func/src/uavcan.equipment.air_data.AngleOfAttack.c \
../LIB/Lib_canard_func/src/uavcan.equipment.air_data.IndicatedAirspeed.c \
../LIB/Lib_canard_func/src/uavcan.equipment.air_data.RawAirData.c \
../LIB/Lib_canard_func/src/uavcan.equipment.air_data.Sideslip.c \
../LIB/Lib_canard_func/src/uavcan.equipment.air_data.StaticPressure.c \
../LIB/Lib_canard_func/src/uavcan.equipment.air_data.StaticTemperature.c \
../LIB/Lib_canard_func/src/uavcan.equipment.air_data.TrueAirspeed.c \
../LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.AngularCommand.c \
../LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.GEOPOICommand.c \
../LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.Mode.c \
../LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.Status.c \
../LIB/Lib_canard_func/src/uavcan.equipment.device.Temperature.c \
../LIB/Lib_canard_func/src/uavcan.equipment.esc.RPMCommand.c \
../LIB/Lib_canard_func/src/uavcan.equipment.esc.RawCommand.c \
../LIB/Lib_canard_func/src/uavcan.equipment.esc.Status.c \
../LIB/Lib_canard_func/src/uavcan.equipment.esc.StatusExtended.c \
../LIB/Lib_canard_func/src/uavcan.equipment.gnss.Auxiliary.c \
../LIB/Lib_canard_func/src/uavcan.equipment.gnss.ECEFPositionVelocity.c \
../LIB/Lib_canard_func/src/uavcan.equipment.gnss.Fix.c \
../LIB/Lib_canard_func/src/uavcan.equipment.gnss.Fix2.c \
../LIB/Lib_canard_func/src/uavcan.equipment.gnss.RTCMStream.c \
../LIB/Lib_canard_func/src/uavcan.equipment.hardpoint.Command.c \
../LIB/Lib_canard_func/src/uavcan.equipment.hardpoint.Status.c \
../LIB/Lib_canard_func/src/uavcan.equipment.ice.FuelTankStatus.c \
../LIB/Lib_canard_func/src/uavcan.equipment.ice.reciprocating.CylinderStatus.c \
../LIB/Lib_canard_func/src/uavcan.equipment.ice.reciprocating.Status.c \
../LIB/Lib_canard_func/src/uavcan.equipment.indication.BeepCommand.c \
../LIB/Lib_canard_func/src/uavcan.equipment.indication.LightsCommand.c \
../LIB/Lib_canard_func/src/uavcan.equipment.indication.RGB565.c \
../LIB/Lib_canard_func/src/uavcan.equipment.indication.SingleLightCommand.c \
../LIB/Lib_canard_func/src/uavcan.equipment.power.BatteryInfo.c \
../LIB/Lib_canard_func/src/uavcan.equipment.power.CircuitStatus.c \
../LIB/Lib_canard_func/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.c \
../LIB/Lib_canard_func/src/uavcan.equipment.range_sensor.Measurement.c \
../LIB/Lib_canard_func/src/uavcan.equipment.safety.ArmingStatus.c \
../LIB/Lib_canard_func/src/uavcan.navigation.GlobalNavigationSolution.c \
../LIB/Lib_canard_func/src/uavcan.protocol.AccessCommandShell_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.AccessCommandShell_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.CANIfaceStats.c \
../LIB/Lib_canard_func/src/uavcan.protocol.DataTypeKind.c \
../LIB/Lib_canard_func/src/uavcan.protocol.GetDataTypeInfo_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.GetDataTypeInfo_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.GetNodeInfo_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.GetNodeInfo_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.GetTransportStats_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.GetTransportStats_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.GlobalTimeSync.c \
../LIB/Lib_canard_func/src/uavcan.protocol.HardwareVersion.c \
../LIB/Lib_canard_func/src/uavcan.protocol.NodeStatus.c \
../LIB/Lib_canard_func/src/uavcan.protocol.Panic.c \
../LIB/Lib_canard_func/src/uavcan.protocol.RestartNode_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.RestartNode_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.SoftwareVersion.c \
../LIB/Lib_canard_func/src/uavcan.protocol.debug.KeyValue.c \
../LIB/Lib_canard_func/src/uavcan.protocol.debug.LogLevel.c \
../LIB/Lib_canard_func/src/uavcan.protocol.debug.LogMessage.c \
../LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.Allocation.c \
../LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.Discovery.c \
../LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.Entry.c \
../LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Begin_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Begin_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Indication.c \
../LIB/Lib_canard_func/src/uavcan.protocol.file.BeginFirmwareUpdate_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.file.BeginFirmwareUpdate_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.file.Delete_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.file.Delete_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.file.EntryType.c \
../LIB/Lib_canard_func/src/uavcan.protocol.file.Error.c \
../LIB/Lib_canard_func/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.file.GetInfo_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.file.GetInfo_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.file.Path.c \
../LIB/Lib_canard_func/src/uavcan.protocol.file.Read_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.file.Read_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.file.Write_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.file.Write_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.param.Empty.c \
../LIB/Lib_canard_func/src/uavcan.protocol.param.ExecuteOpcode_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.param.ExecuteOpcode_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.param.GetSet_req.c \
../LIB/Lib_canard_func/src/uavcan.protocol.param.GetSet_res.c \
../LIB/Lib_canard_func/src/uavcan.protocol.param.NumericValue.c \
../LIB/Lib_canard_func/src/uavcan.protocol.param.Value.c \
../LIB/Lib_canard_func/src/uavcan.tunnel.Broadcast.c \
../LIB/Lib_canard_func/src/uavcan.tunnel.Call_req.c \
../LIB/Lib_canard_func/src/uavcan.tunnel.Call_res.c \
../LIB/Lib_canard_func/src/uavcan.tunnel.Protocol.c \
../LIB/Lib_canard_func/src/uavcan.tunnel.SerialConfig.c \
../LIB/Lib_canard_func/src/uavcan.tunnel.Targetted.c 

OBJS += \
./LIB/Lib_canard_func/src/uavcan.CoarseOrientation.o \
./LIB/Lib_canard_func/src/uavcan.Timestamp.o \
./LIB/Lib_canard_func/src/uavcan.equipment.actuator.ArrayCommand.o \
./LIB/Lib_canard_func/src/uavcan.equipment.actuator.Command.o \
./LIB/Lib_canard_func/src/uavcan.equipment.actuator.Status.o \
./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.MagneticFieldStrength.o \
./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.MagneticFieldStrength2.o \
./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.RawIMU.o \
./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.Solution.o \
./LIB/Lib_canard_func/src/uavcan.equipment.air_data.AngleOfAttack.o \
./LIB/Lib_canard_func/src/uavcan.equipment.air_data.IndicatedAirspeed.o \
./LIB/Lib_canard_func/src/uavcan.equipment.air_data.RawAirData.o \
./LIB/Lib_canard_func/src/uavcan.equipment.air_data.Sideslip.o \
./LIB/Lib_canard_func/src/uavcan.equipment.air_data.StaticPressure.o \
./LIB/Lib_canard_func/src/uavcan.equipment.air_data.StaticTemperature.o \
./LIB/Lib_canard_func/src/uavcan.equipment.air_data.TrueAirspeed.o \
./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.AngularCommand.o \
./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.GEOPOICommand.o \
./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.Mode.o \
./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.Status.o \
./LIB/Lib_canard_func/src/uavcan.equipment.device.Temperature.o \
./LIB/Lib_canard_func/src/uavcan.equipment.esc.RPMCommand.o \
./LIB/Lib_canard_func/src/uavcan.equipment.esc.RawCommand.o \
./LIB/Lib_canard_func/src/uavcan.equipment.esc.Status.o \
./LIB/Lib_canard_func/src/uavcan.equipment.esc.StatusExtended.o \
./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Auxiliary.o \
./LIB/Lib_canard_func/src/uavcan.equipment.gnss.ECEFPositionVelocity.o \
./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Fix.o \
./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Fix2.o \
./LIB/Lib_canard_func/src/uavcan.equipment.gnss.RTCMStream.o \
./LIB/Lib_canard_func/src/uavcan.equipment.hardpoint.Command.o \
./LIB/Lib_canard_func/src/uavcan.equipment.hardpoint.Status.o \
./LIB/Lib_canard_func/src/uavcan.equipment.ice.FuelTankStatus.o \
./LIB/Lib_canard_func/src/uavcan.equipment.ice.reciprocating.CylinderStatus.o \
./LIB/Lib_canard_func/src/uavcan.equipment.ice.reciprocating.Status.o \
./LIB/Lib_canard_func/src/uavcan.equipment.indication.BeepCommand.o \
./LIB/Lib_canard_func/src/uavcan.equipment.indication.LightsCommand.o \
./LIB/Lib_canard_func/src/uavcan.equipment.indication.RGB565.o \
./LIB/Lib_canard_func/src/uavcan.equipment.indication.SingleLightCommand.o \
./LIB/Lib_canard_func/src/uavcan.equipment.power.BatteryInfo.o \
./LIB/Lib_canard_func/src/uavcan.equipment.power.CircuitStatus.o \
./LIB/Lib_canard_func/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.o \
./LIB/Lib_canard_func/src/uavcan.equipment.range_sensor.Measurement.o \
./LIB/Lib_canard_func/src/uavcan.equipment.safety.ArmingStatus.o \
./LIB/Lib_canard_func/src/uavcan.navigation.GlobalNavigationSolution.o \
./LIB/Lib_canard_func/src/uavcan.protocol.AccessCommandShell_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.AccessCommandShell_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.CANIfaceStats.o \
./LIB/Lib_canard_func/src/uavcan.protocol.DataTypeKind.o \
./LIB/Lib_canard_func/src/uavcan.protocol.GetDataTypeInfo_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.GetDataTypeInfo_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.GetNodeInfo_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.GetNodeInfo_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.GetTransportStats_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.GetTransportStats_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.GlobalTimeSync.o \
./LIB/Lib_canard_func/src/uavcan.protocol.HardwareVersion.o \
./LIB/Lib_canard_func/src/uavcan.protocol.NodeStatus.o \
./LIB/Lib_canard_func/src/uavcan.protocol.Panic.o \
./LIB/Lib_canard_func/src/uavcan.protocol.RestartNode_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.RestartNode_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.SoftwareVersion.o \
./LIB/Lib_canard_func/src/uavcan.protocol.debug.KeyValue.o \
./LIB/Lib_canard_func/src/uavcan.protocol.debug.LogLevel.o \
./LIB/Lib_canard_func/src/uavcan.protocol.debug.LogMessage.o \
./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.Allocation.o \
./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.Discovery.o \
./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.Entry.o \
./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Begin_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Begin_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Indication.o \
./LIB/Lib_canard_func/src/uavcan.protocol.file.BeginFirmwareUpdate_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.file.BeginFirmwareUpdate_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Delete_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Delete_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.file.EntryType.o \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Error.o \
./LIB/Lib_canard_func/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.file.GetInfo_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.file.GetInfo_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Path.o \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Read_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Read_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Write_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Write_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.param.Empty.o \
./LIB/Lib_canard_func/src/uavcan.protocol.param.ExecuteOpcode_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.param.ExecuteOpcode_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.param.GetSet_req.o \
./LIB/Lib_canard_func/src/uavcan.protocol.param.GetSet_res.o \
./LIB/Lib_canard_func/src/uavcan.protocol.param.NumericValue.o \
./LIB/Lib_canard_func/src/uavcan.protocol.param.Value.o \
./LIB/Lib_canard_func/src/uavcan.tunnel.Broadcast.o \
./LIB/Lib_canard_func/src/uavcan.tunnel.Call_req.o \
./LIB/Lib_canard_func/src/uavcan.tunnel.Call_res.o \
./LIB/Lib_canard_func/src/uavcan.tunnel.Protocol.o \
./LIB/Lib_canard_func/src/uavcan.tunnel.SerialConfig.o \
./LIB/Lib_canard_func/src/uavcan.tunnel.Targetted.o 

C_DEPS += \
./LIB/Lib_canard_func/src/uavcan.CoarseOrientation.d \
./LIB/Lib_canard_func/src/uavcan.Timestamp.d \
./LIB/Lib_canard_func/src/uavcan.equipment.actuator.ArrayCommand.d \
./LIB/Lib_canard_func/src/uavcan.equipment.actuator.Command.d \
./LIB/Lib_canard_func/src/uavcan.equipment.actuator.Status.d \
./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.MagneticFieldStrength.d \
./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.MagneticFieldStrength2.d \
./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.RawIMU.d \
./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.Solution.d \
./LIB/Lib_canard_func/src/uavcan.equipment.air_data.AngleOfAttack.d \
./LIB/Lib_canard_func/src/uavcan.equipment.air_data.IndicatedAirspeed.d \
./LIB/Lib_canard_func/src/uavcan.equipment.air_data.RawAirData.d \
./LIB/Lib_canard_func/src/uavcan.equipment.air_data.Sideslip.d \
./LIB/Lib_canard_func/src/uavcan.equipment.air_data.StaticPressure.d \
./LIB/Lib_canard_func/src/uavcan.equipment.air_data.StaticTemperature.d \
./LIB/Lib_canard_func/src/uavcan.equipment.air_data.TrueAirspeed.d \
./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.AngularCommand.d \
./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.GEOPOICommand.d \
./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.Mode.d \
./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.Status.d \
./LIB/Lib_canard_func/src/uavcan.equipment.device.Temperature.d \
./LIB/Lib_canard_func/src/uavcan.equipment.esc.RPMCommand.d \
./LIB/Lib_canard_func/src/uavcan.equipment.esc.RawCommand.d \
./LIB/Lib_canard_func/src/uavcan.equipment.esc.Status.d \
./LIB/Lib_canard_func/src/uavcan.equipment.esc.StatusExtended.d \
./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Auxiliary.d \
./LIB/Lib_canard_func/src/uavcan.equipment.gnss.ECEFPositionVelocity.d \
./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Fix.d \
./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Fix2.d \
./LIB/Lib_canard_func/src/uavcan.equipment.gnss.RTCMStream.d \
./LIB/Lib_canard_func/src/uavcan.equipment.hardpoint.Command.d \
./LIB/Lib_canard_func/src/uavcan.equipment.hardpoint.Status.d \
./LIB/Lib_canard_func/src/uavcan.equipment.ice.FuelTankStatus.d \
./LIB/Lib_canard_func/src/uavcan.equipment.ice.reciprocating.CylinderStatus.d \
./LIB/Lib_canard_func/src/uavcan.equipment.ice.reciprocating.Status.d \
./LIB/Lib_canard_func/src/uavcan.equipment.indication.BeepCommand.d \
./LIB/Lib_canard_func/src/uavcan.equipment.indication.LightsCommand.d \
./LIB/Lib_canard_func/src/uavcan.equipment.indication.RGB565.d \
./LIB/Lib_canard_func/src/uavcan.equipment.indication.SingleLightCommand.d \
./LIB/Lib_canard_func/src/uavcan.equipment.power.BatteryInfo.d \
./LIB/Lib_canard_func/src/uavcan.equipment.power.CircuitStatus.d \
./LIB/Lib_canard_func/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.d \
./LIB/Lib_canard_func/src/uavcan.equipment.range_sensor.Measurement.d \
./LIB/Lib_canard_func/src/uavcan.equipment.safety.ArmingStatus.d \
./LIB/Lib_canard_func/src/uavcan.navigation.GlobalNavigationSolution.d \
./LIB/Lib_canard_func/src/uavcan.protocol.AccessCommandShell_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.AccessCommandShell_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.CANIfaceStats.d \
./LIB/Lib_canard_func/src/uavcan.protocol.DataTypeKind.d \
./LIB/Lib_canard_func/src/uavcan.protocol.GetDataTypeInfo_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.GetDataTypeInfo_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.GetNodeInfo_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.GetNodeInfo_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.GetTransportStats_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.GetTransportStats_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.GlobalTimeSync.d \
./LIB/Lib_canard_func/src/uavcan.protocol.HardwareVersion.d \
./LIB/Lib_canard_func/src/uavcan.protocol.NodeStatus.d \
./LIB/Lib_canard_func/src/uavcan.protocol.Panic.d \
./LIB/Lib_canard_func/src/uavcan.protocol.RestartNode_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.RestartNode_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.SoftwareVersion.d \
./LIB/Lib_canard_func/src/uavcan.protocol.debug.KeyValue.d \
./LIB/Lib_canard_func/src/uavcan.protocol.debug.LogLevel.d \
./LIB/Lib_canard_func/src/uavcan.protocol.debug.LogMessage.d \
./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.Allocation.d \
./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.Discovery.d \
./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.Entry.d \
./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Begin_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Begin_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Indication.d \
./LIB/Lib_canard_func/src/uavcan.protocol.file.BeginFirmwareUpdate_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.file.BeginFirmwareUpdate_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Delete_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Delete_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.file.EntryType.d \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Error.d \
./LIB/Lib_canard_func/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.file.GetInfo_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.file.GetInfo_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Path.d \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Read_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Read_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Write_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.file.Write_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.param.Empty.d \
./LIB/Lib_canard_func/src/uavcan.protocol.param.ExecuteOpcode_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.param.ExecuteOpcode_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.param.GetSet_req.d \
./LIB/Lib_canard_func/src/uavcan.protocol.param.GetSet_res.d \
./LIB/Lib_canard_func/src/uavcan.protocol.param.NumericValue.d \
./LIB/Lib_canard_func/src/uavcan.protocol.param.Value.d \
./LIB/Lib_canard_func/src/uavcan.tunnel.Broadcast.d \
./LIB/Lib_canard_func/src/uavcan.tunnel.Call_req.d \
./LIB/Lib_canard_func/src/uavcan.tunnel.Call_res.d \
./LIB/Lib_canard_func/src/uavcan.tunnel.Protocol.d \
./LIB/Lib_canard_func/src/uavcan.tunnel.SerialConfig.d \
./LIB/Lib_canard_func/src/uavcan.tunnel.Targetted.d 


# Each subdirectory must supply rules for building sources it contributes
LIB/Lib_canard_func/src/%.o LIB/Lib_canard_func/src/%.su LIB/Lib_canard_func/src/%.cyclo: ../LIB/Lib_canard_func/src/%.c LIB/Lib_canard_func/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F407xx -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"/home/duong/Du_an/HYPMOTION/DEV_TO_IDE/pack_pin_ide/pack_pin/LIB/canard" -I"/home/duong/Du_an/HYPMOTION/DEV_TO_IDE/pack_pin_ide/pack_pin/LIB/Lib_canard_func/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-LIB-2f-Lib_canard_func-2f-src

clean-LIB-2f-Lib_canard_func-2f-src:
	-$(RM) ./LIB/Lib_canard_func/src/uavcan.CoarseOrientation.cyclo ./LIB/Lib_canard_func/src/uavcan.CoarseOrientation.d ./LIB/Lib_canard_func/src/uavcan.CoarseOrientation.o ./LIB/Lib_canard_func/src/uavcan.CoarseOrientation.su ./LIB/Lib_canard_func/src/uavcan.Timestamp.cyclo ./LIB/Lib_canard_func/src/uavcan.Timestamp.d ./LIB/Lib_canard_func/src/uavcan.Timestamp.o ./LIB/Lib_canard_func/src/uavcan.Timestamp.su ./LIB/Lib_canard_func/src/uavcan.equipment.actuator.ArrayCommand.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.actuator.ArrayCommand.d ./LIB/Lib_canard_func/src/uavcan.equipment.actuator.ArrayCommand.o ./LIB/Lib_canard_func/src/uavcan.equipment.actuator.ArrayCommand.su ./LIB/Lib_canard_func/src/uavcan.equipment.actuator.Command.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.actuator.Command.d ./LIB/Lib_canard_func/src/uavcan.equipment.actuator.Command.o ./LIB/Lib_canard_func/src/uavcan.equipment.actuator.Command.su ./LIB/Lib_canard_func/src/uavcan.equipment.actuator.Status.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.actuator.Status.d ./LIB/Lib_canard_func/src/uavcan.equipment.actuator.Status.o ./LIB/Lib_canard_func/src/uavcan.equipment.actuator.Status.su ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.MagneticFieldStrength.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.MagneticFieldStrength.d ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.MagneticFieldStrength.o ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.MagneticFieldStrength.su ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.MagneticFieldStrength2.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.MagneticFieldStrength2.d ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.MagneticFieldStrength2.o ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.MagneticFieldStrength2.su ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.RawIMU.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.RawIMU.d ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.RawIMU.o ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.RawIMU.su ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.Solution.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.Solution.d ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.Solution.o ./LIB/Lib_canard_func/src/uavcan.equipment.ahrs.Solution.su ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.AngleOfAttack.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.AngleOfAttack.d ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.AngleOfAttack.o ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.AngleOfAttack.su ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.IndicatedAirspeed.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.IndicatedAirspeed.d ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.IndicatedAirspeed.o ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.IndicatedAirspeed.su ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.RawAirData.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.RawAirData.d ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.RawAirData.o ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.RawAirData.su ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.Sideslip.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.Sideslip.d ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.Sideslip.o ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.Sideslip.su ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.StaticPressure.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.StaticPressure.d ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.StaticPressure.o ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.StaticPressure.su ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.StaticTemperature.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.StaticTemperature.d ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.StaticTemperature.o ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.StaticTemperature.su ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.TrueAirspeed.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.TrueAirspeed.d ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.TrueAirspeed.o ./LIB/Lib_canard_func/src/uavcan.equipment.air_data.TrueAirspeed.su ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.AngularCommand.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.AngularCommand.d ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.AngularCommand.o ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.AngularCommand.su ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.GEOPOICommand.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.GEOPOICommand.d ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.GEOPOICommand.o ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.GEOPOICommand.su ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.Mode.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.Mode.d ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.Mode.o ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.Mode.su ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.Status.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.Status.d ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.Status.o ./LIB/Lib_canard_func/src/uavcan.equipment.camera_gimbal.Status.su ./LIB/Lib_canard_func/src/uavcan.equipment.device.Temperature.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.device.Temperature.d ./LIB/Lib_canard_func/src/uavcan.equipment.device.Temperature.o ./LIB/Lib_canard_func/src/uavcan.equipment.device.Temperature.su ./LIB/Lib_canard_func/src/uavcan.equipment.esc.RPMCommand.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.esc.RPMCommand.d ./LIB/Lib_canard_func/src/uavcan.equipment.esc.RPMCommand.o ./LIB/Lib_canard_func/src/uavcan.equipment.esc.RPMCommand.su ./LIB/Lib_canard_func/src/uavcan.equipment.esc.RawCommand.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.esc.RawCommand.d
	-$(RM) ./LIB/Lib_canard_func/src/uavcan.equipment.esc.RawCommand.o ./LIB/Lib_canard_func/src/uavcan.equipment.esc.RawCommand.su ./LIB/Lib_canard_func/src/uavcan.equipment.esc.Status.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.esc.Status.d ./LIB/Lib_canard_func/src/uavcan.equipment.esc.Status.o ./LIB/Lib_canard_func/src/uavcan.equipment.esc.Status.su ./LIB/Lib_canard_func/src/uavcan.equipment.esc.StatusExtended.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.esc.StatusExtended.d ./LIB/Lib_canard_func/src/uavcan.equipment.esc.StatusExtended.o ./LIB/Lib_canard_func/src/uavcan.equipment.esc.StatusExtended.su ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Auxiliary.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Auxiliary.d ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Auxiliary.o ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Auxiliary.su ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.ECEFPositionVelocity.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.ECEFPositionVelocity.d ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.ECEFPositionVelocity.o ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.ECEFPositionVelocity.su ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Fix.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Fix.d ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Fix.o ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Fix.su ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Fix2.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Fix2.d ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Fix2.o ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.Fix2.su ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.RTCMStream.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.RTCMStream.d ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.RTCMStream.o ./LIB/Lib_canard_func/src/uavcan.equipment.gnss.RTCMStream.su ./LIB/Lib_canard_func/src/uavcan.equipment.hardpoint.Command.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.hardpoint.Command.d ./LIB/Lib_canard_func/src/uavcan.equipment.hardpoint.Command.o ./LIB/Lib_canard_func/src/uavcan.equipment.hardpoint.Command.su ./LIB/Lib_canard_func/src/uavcan.equipment.hardpoint.Status.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.hardpoint.Status.d ./LIB/Lib_canard_func/src/uavcan.equipment.hardpoint.Status.o ./LIB/Lib_canard_func/src/uavcan.equipment.hardpoint.Status.su ./LIB/Lib_canard_func/src/uavcan.equipment.ice.FuelTankStatus.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.ice.FuelTankStatus.d ./LIB/Lib_canard_func/src/uavcan.equipment.ice.FuelTankStatus.o ./LIB/Lib_canard_func/src/uavcan.equipment.ice.FuelTankStatus.su ./LIB/Lib_canard_func/src/uavcan.equipment.ice.reciprocating.CylinderStatus.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.ice.reciprocating.CylinderStatus.d ./LIB/Lib_canard_func/src/uavcan.equipment.ice.reciprocating.CylinderStatus.o ./LIB/Lib_canard_func/src/uavcan.equipment.ice.reciprocating.CylinderStatus.su ./LIB/Lib_canard_func/src/uavcan.equipment.ice.reciprocating.Status.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.ice.reciprocating.Status.d ./LIB/Lib_canard_func/src/uavcan.equipment.ice.reciprocating.Status.o ./LIB/Lib_canard_func/src/uavcan.equipment.ice.reciprocating.Status.su ./LIB/Lib_canard_func/src/uavcan.equipment.indication.BeepCommand.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.indication.BeepCommand.d ./LIB/Lib_canard_func/src/uavcan.equipment.indication.BeepCommand.o ./LIB/Lib_canard_func/src/uavcan.equipment.indication.BeepCommand.su ./LIB/Lib_canard_func/src/uavcan.equipment.indication.LightsCommand.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.indication.LightsCommand.d ./LIB/Lib_canard_func/src/uavcan.equipment.indication.LightsCommand.o ./LIB/Lib_canard_func/src/uavcan.equipment.indication.LightsCommand.su ./LIB/Lib_canard_func/src/uavcan.equipment.indication.RGB565.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.indication.RGB565.d ./LIB/Lib_canard_func/src/uavcan.equipment.indication.RGB565.o ./LIB/Lib_canard_func/src/uavcan.equipment.indication.RGB565.su ./LIB/Lib_canard_func/src/uavcan.equipment.indication.SingleLightCommand.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.indication.SingleLightCommand.d ./LIB/Lib_canard_func/src/uavcan.equipment.indication.SingleLightCommand.o ./LIB/Lib_canard_func/src/uavcan.equipment.indication.SingleLightCommand.su ./LIB/Lib_canard_func/src/uavcan.equipment.power.BatteryInfo.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.power.BatteryInfo.d ./LIB/Lib_canard_func/src/uavcan.equipment.power.BatteryInfo.o ./LIB/Lib_canard_func/src/uavcan.equipment.power.BatteryInfo.su ./LIB/Lib_canard_func/src/uavcan.equipment.power.CircuitStatus.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.power.CircuitStatus.d ./LIB/Lib_canard_func/src/uavcan.equipment.power.CircuitStatus.o ./LIB/Lib_canard_func/src/uavcan.equipment.power.CircuitStatus.su ./LIB/Lib_canard_func/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.d ./LIB/Lib_canard_func/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.o ./LIB/Lib_canard_func/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.su ./LIB/Lib_canard_func/src/uavcan.equipment.range_sensor.Measurement.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.range_sensor.Measurement.d ./LIB/Lib_canard_func/src/uavcan.equipment.range_sensor.Measurement.o ./LIB/Lib_canard_func/src/uavcan.equipment.range_sensor.Measurement.su ./LIB/Lib_canard_func/src/uavcan.equipment.safety.ArmingStatus.cyclo ./LIB/Lib_canard_func/src/uavcan.equipment.safety.ArmingStatus.d ./LIB/Lib_canard_func/src/uavcan.equipment.safety.ArmingStatus.o ./LIB/Lib_canard_func/src/uavcan.equipment.safety.ArmingStatus.su ./LIB/Lib_canard_func/src/uavcan.navigation.GlobalNavigationSolution.cyclo ./LIB/Lib_canard_func/src/uavcan.navigation.GlobalNavigationSolution.d ./LIB/Lib_canard_func/src/uavcan.navigation.GlobalNavigationSolution.o
	-$(RM) ./LIB/Lib_canard_func/src/uavcan.navigation.GlobalNavigationSolution.su ./LIB/Lib_canard_func/src/uavcan.protocol.AccessCommandShell_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.AccessCommandShell_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.AccessCommandShell_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.AccessCommandShell_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.AccessCommandShell_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.AccessCommandShell_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.AccessCommandShell_res.o ./LIB/Lib_canard_func/src/uavcan.protocol.AccessCommandShell_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.CANIfaceStats.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.CANIfaceStats.d ./LIB/Lib_canard_func/src/uavcan.protocol.CANIfaceStats.o ./LIB/Lib_canard_func/src/uavcan.protocol.CANIfaceStats.su ./LIB/Lib_canard_func/src/uavcan.protocol.DataTypeKind.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.DataTypeKind.d ./LIB/Lib_canard_func/src/uavcan.protocol.DataTypeKind.o ./LIB/Lib_canard_func/src/uavcan.protocol.DataTypeKind.su ./LIB/Lib_canard_func/src/uavcan.protocol.GetDataTypeInfo_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.GetDataTypeInfo_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.GetDataTypeInfo_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.GetDataTypeInfo_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.GetDataTypeInfo_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.GetDataTypeInfo_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.GetDataTypeInfo_res.o ./LIB/Lib_canard_func/src/uavcan.protocol.GetDataTypeInfo_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.GetNodeInfo_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.GetNodeInfo_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.GetNodeInfo_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.GetNodeInfo_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.GetNodeInfo_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.GetNodeInfo_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.GetNodeInfo_res.o ./LIB/Lib_canard_func/src/uavcan.protocol.GetNodeInfo_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.GetTransportStats_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.GetTransportStats_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.GetTransportStats_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.GetTransportStats_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.GetTransportStats_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.GetTransportStats_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.GetTransportStats_res.o ./LIB/Lib_canard_func/src/uavcan.protocol.GetTransportStats_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.GlobalTimeSync.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.GlobalTimeSync.d ./LIB/Lib_canard_func/src/uavcan.protocol.GlobalTimeSync.o ./LIB/Lib_canard_func/src/uavcan.protocol.GlobalTimeSync.su ./LIB/Lib_canard_func/src/uavcan.protocol.HardwareVersion.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.HardwareVersion.d ./LIB/Lib_canard_func/src/uavcan.protocol.HardwareVersion.o ./LIB/Lib_canard_func/src/uavcan.protocol.HardwareVersion.su ./LIB/Lib_canard_func/src/uavcan.protocol.NodeStatus.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.NodeStatus.d ./LIB/Lib_canard_func/src/uavcan.protocol.NodeStatus.o ./LIB/Lib_canard_func/src/uavcan.protocol.NodeStatus.su ./LIB/Lib_canard_func/src/uavcan.protocol.Panic.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.Panic.d ./LIB/Lib_canard_func/src/uavcan.protocol.Panic.o ./LIB/Lib_canard_func/src/uavcan.protocol.Panic.su ./LIB/Lib_canard_func/src/uavcan.protocol.RestartNode_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.RestartNode_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.RestartNode_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.RestartNode_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.RestartNode_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.RestartNode_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.RestartNode_res.o ./LIB/Lib_canard_func/src/uavcan.protocol.RestartNode_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.SoftwareVersion.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.SoftwareVersion.d ./LIB/Lib_canard_func/src/uavcan.protocol.SoftwareVersion.o ./LIB/Lib_canard_func/src/uavcan.protocol.SoftwareVersion.su ./LIB/Lib_canard_func/src/uavcan.protocol.debug.KeyValue.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.debug.KeyValue.d ./LIB/Lib_canard_func/src/uavcan.protocol.debug.KeyValue.o ./LIB/Lib_canard_func/src/uavcan.protocol.debug.KeyValue.su ./LIB/Lib_canard_func/src/uavcan.protocol.debug.LogLevel.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.debug.LogLevel.d ./LIB/Lib_canard_func/src/uavcan.protocol.debug.LogLevel.o ./LIB/Lib_canard_func/src/uavcan.protocol.debug.LogLevel.su ./LIB/Lib_canard_func/src/uavcan.protocol.debug.LogMessage.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.debug.LogMessage.d ./LIB/Lib_canard_func/src/uavcan.protocol.debug.LogMessage.o ./LIB/Lib_canard_func/src/uavcan.protocol.debug.LogMessage.su ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.Allocation.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.Allocation.d ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.Allocation.o ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.Allocation.su ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.o
	-$(RM) ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.Discovery.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.Discovery.d ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.Discovery.o ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.Discovery.su ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.Entry.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.Entry.d ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.Entry.o ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.Entry.su ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.o ./LIB/Lib_canard_func/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Begin_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Begin_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Begin_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Begin_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Begin_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Begin_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Begin_res.o ./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Begin_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Indication.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Indication.d ./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Indication.o ./LIB/Lib_canard_func/src/uavcan.protocol.enumeration.Indication.su ./LIB/Lib_canard_func/src/uavcan.protocol.file.BeginFirmwareUpdate_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.file.BeginFirmwareUpdate_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.file.BeginFirmwareUpdate_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.file.BeginFirmwareUpdate_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.file.BeginFirmwareUpdate_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.file.BeginFirmwareUpdate_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.file.BeginFirmwareUpdate_res.o ./LIB/Lib_canard_func/src/uavcan.protocol.file.BeginFirmwareUpdate_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.file.Delete_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.file.Delete_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.file.Delete_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.file.Delete_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.file.Delete_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.file.Delete_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.file.Delete_res.o ./LIB/Lib_canard_func/src/uavcan.protocol.file.Delete_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.file.EntryType.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.file.EntryType.d ./LIB/Lib_canard_func/src/uavcan.protocol.file.EntryType.o ./LIB/Lib_canard_func/src/uavcan.protocol.file.EntryType.su ./LIB/Lib_canard_func/src/uavcan.protocol.file.Error.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.file.Error.d ./LIB/Lib_canard_func/src/uavcan.protocol.file.Error.o ./LIB/Lib_canard_func/src/uavcan.protocol.file.Error.su ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.o ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetInfo_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetInfo_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetInfo_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetInfo_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetInfo_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetInfo_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetInfo_res.o ./LIB/Lib_canard_func/src/uavcan.protocol.file.GetInfo_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.file.Path.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.file.Path.d ./LIB/Lib_canard_func/src/uavcan.protocol.file.Path.o ./LIB/Lib_canard_func/src/uavcan.protocol.file.Path.su ./LIB/Lib_canard_func/src/uavcan.protocol.file.Read_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.file.Read_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.file.Read_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.file.Read_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.file.Read_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.file.Read_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.file.Read_res.o ./LIB/Lib_canard_func/src/uavcan.protocol.file.Read_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.file.Write_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.file.Write_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.file.Write_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.file.Write_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.file.Write_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.file.Write_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.file.Write_res.o
	-$(RM) ./LIB/Lib_canard_func/src/uavcan.protocol.file.Write_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.param.Empty.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.param.Empty.d ./LIB/Lib_canard_func/src/uavcan.protocol.param.Empty.o ./LIB/Lib_canard_func/src/uavcan.protocol.param.Empty.su ./LIB/Lib_canard_func/src/uavcan.protocol.param.ExecuteOpcode_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.param.ExecuteOpcode_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.param.ExecuteOpcode_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.param.ExecuteOpcode_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.param.ExecuteOpcode_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.param.ExecuteOpcode_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.param.ExecuteOpcode_res.o ./LIB/Lib_canard_func/src/uavcan.protocol.param.ExecuteOpcode_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.param.GetSet_req.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.param.GetSet_req.d ./LIB/Lib_canard_func/src/uavcan.protocol.param.GetSet_req.o ./LIB/Lib_canard_func/src/uavcan.protocol.param.GetSet_req.su ./LIB/Lib_canard_func/src/uavcan.protocol.param.GetSet_res.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.param.GetSet_res.d ./LIB/Lib_canard_func/src/uavcan.protocol.param.GetSet_res.o ./LIB/Lib_canard_func/src/uavcan.protocol.param.GetSet_res.su ./LIB/Lib_canard_func/src/uavcan.protocol.param.NumericValue.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.param.NumericValue.d ./LIB/Lib_canard_func/src/uavcan.protocol.param.NumericValue.o ./LIB/Lib_canard_func/src/uavcan.protocol.param.NumericValue.su ./LIB/Lib_canard_func/src/uavcan.protocol.param.Value.cyclo ./LIB/Lib_canard_func/src/uavcan.protocol.param.Value.d ./LIB/Lib_canard_func/src/uavcan.protocol.param.Value.o ./LIB/Lib_canard_func/src/uavcan.protocol.param.Value.su ./LIB/Lib_canard_func/src/uavcan.tunnel.Broadcast.cyclo ./LIB/Lib_canard_func/src/uavcan.tunnel.Broadcast.d ./LIB/Lib_canard_func/src/uavcan.tunnel.Broadcast.o ./LIB/Lib_canard_func/src/uavcan.tunnel.Broadcast.su ./LIB/Lib_canard_func/src/uavcan.tunnel.Call_req.cyclo ./LIB/Lib_canard_func/src/uavcan.tunnel.Call_req.d ./LIB/Lib_canard_func/src/uavcan.tunnel.Call_req.o ./LIB/Lib_canard_func/src/uavcan.tunnel.Call_req.su ./LIB/Lib_canard_func/src/uavcan.tunnel.Call_res.cyclo ./LIB/Lib_canard_func/src/uavcan.tunnel.Call_res.d ./LIB/Lib_canard_func/src/uavcan.tunnel.Call_res.o ./LIB/Lib_canard_func/src/uavcan.tunnel.Call_res.su ./LIB/Lib_canard_func/src/uavcan.tunnel.Protocol.cyclo ./LIB/Lib_canard_func/src/uavcan.tunnel.Protocol.d ./LIB/Lib_canard_func/src/uavcan.tunnel.Protocol.o ./LIB/Lib_canard_func/src/uavcan.tunnel.Protocol.su ./LIB/Lib_canard_func/src/uavcan.tunnel.SerialConfig.cyclo ./LIB/Lib_canard_func/src/uavcan.tunnel.SerialConfig.d ./LIB/Lib_canard_func/src/uavcan.tunnel.SerialConfig.o ./LIB/Lib_canard_func/src/uavcan.tunnel.SerialConfig.su ./LIB/Lib_canard_func/src/uavcan.tunnel.Targetted.cyclo ./LIB/Lib_canard_func/src/uavcan.tunnel.Targetted.d ./LIB/Lib_canard_func/src/uavcan.tunnel.Targetted.o ./LIB/Lib_canard_func/src/uavcan.tunnel.Targetted.su

.PHONY: clean-LIB-2f-Lib_canard_func-2f-src

